README.md

Link to Go docs as proposed by @mbrt, use text by @mbrt 
replaces #9

add $PATH, $GOPATH mentions

---

pkg/config/config_test.go
pkg/filter/convert.go
pkg/filter/convert_test.go

Unit tests were not good enough to catch the fact that const
resolution was swallowing up the list filter.
Closes #17

fix list filter

---

cmd/gmailctl/cmd/edit_cmd.go
cmd/gmailctl/cmd/io.go

This change makes it more obvious as to what happen when an
edit has failed, and gives more options when possible.
Close #43.

Improve feedback on edit failure cases.

---

cmd/gmailctl/cmd/io.go

On Windows, `gmailctl edit` was always printing "invalid choice".
Because the switch would always use a string ending in `\r`.

Fix broken askYN on Windows

---

pkg/export/api/api_import.go

The fix involves rewriting the filter, but doesn't affect the diff
negatively, because the same code is used. Whenever the filter is
changed, the rewritten version (without the negatedQuery field) will
be used.
Close #69.

Fix import of filters with non-empty negatedQuery.

---

cmd/gmailctl/cmd/init_cmd.go

It was especially confusing for gSuite users.
Close #91.

Make init instructions more clear.

---

README.md

The `README.md` file is a little lengthy, it would be nice to easily go to what you're looking for in the documentation.

Added a ToC in README.md

---

README.md

I've submitted [a pull request to Homebrew](https://github.com/Homebrew/homebrew-core/pull/52674) to add a formula for gmailctl. If it gets accepted, it would be worth mentioning this installation method for macOS users in the readme.

Mention installation via Homebrew

---

pkg/export/api/api_export.go
pkg/parser/parser.go
pkg/rimport/rimport.go

This addresses the issue reported in #53. Unfortunately syntax errors cannot be printed in a better way, because of limitations in the `jsonnet` and `encoding/json` packages.

Error reporting

---

hack/check-codegen.sh

The purpose is checking whether the `go gen` is up to date or not, not checking whether the dependencies are 100% clean.

Avoid checking go.sum

---

README.md
cmd/gmailctl/cmd/export_cmd.go
docs/v1alpha2.md
pkg/filter/convert.go

Fix a typo of "default", as well as conversions of "allow(s) to" -> "allow(s) one to". Identified by Debian's lintian.

Fix a couple of spelling errors

---

README.md

As defined in the struct
(https://github.com/mbrt/gmailctl/blob/master/pkg/config/v1alpha3/config.go#L185)
field name for list of mailing lists is called `lists`.

Fix doc on test message fields

---

pkg/filter/convert.go
pkg/filter/convert_test.go
pkg/parser/ast.go
testdata/local.bigsplit.diff
testdata/local.bigsplit.jsonnet

Split long filters

---

.github/workflows/codeql-analysis.yml
hack/check-codegen.sh

The analysis was complaining that `git checkout HEAD^2` is no longer
necessary:
```
1 issue was detected with this workflow: git checkout HEAD^2 is no
longer necessary. Please remove this step as Code Scanning recommends
analyzing the merge commit for best results.
```

Update CodeQL workflow.

---

README.md

The example for tests is incorrect and does not compile because the `to` field must be an array of strings. As it stands the example will result in an error `cannot unmarshal string into Go struct field Message.tests.messages.to of type []string`.
Thanks for a super valuable piece of software! I'm loving Gmailctl.

Fix testing example in README

---

cmd/gmailctl/cmd/init_cmd.go
pkg/api/api.go
pkg/api/auth.go

The GmailMetatadaScope is a leftover from the beginning of times and
it's not realy necessary.
No APIs gmailctl is using require the scope, so it was removed.
Follow up from #204.

Remove unused GMail auth scope.

---

internal/stringset/stringset.go

The coverage improves and we don't have to add an additional license.

Remove all unused methods from stringset.

---

internal/engine/filter/diff_test.go
internal/engine/filter/filter.go
testdata/valid/02-add-one.diff
testdata/valid/03-labels.diff
testdata/valid/05-bigdiff.diff
testdata/valid/06-bigsplit.diff
testdata/valid/07-deleteall.diff

Makes for easier-to-read diffs.
Close #221.

Indent filter criteria

---

.gitignore
README.md
cmd/gmailctl/localcred/local_provider.go
cmd/gmailctl/localcred/oauth2_server.go
internal/engine/api/api.go
internal/engine/api/auth.go

Google recently tightened controls on unverified apps. This caused trouble to new users creating their credentials.
The workflow now requires a local webserver and the browser from which the user authenticates needs to run on the same machine as gmailctl, every time the token needs a refresh.
Close #232, #243.

Update authorization workflow

---

cmd/gmailctl/cmd/edit_cmd.go

Fixes Issue #249
The second argument of `As` must be a pointer: https://pkg.go.dev/errors

Bugfix: Second arg of As is a pointer

---

README.md
cmd/gmailctl/cmd/diff_cmd.go

* Update diff_cmd.go
* Update README.md
PS: Thank you for creating and maintaining this tool.

Fix typo in diff command description (configuaration)

---

README.md

I'm a Fedora Linux packager and I have just added gmailctl to the Fedora repositories.
I would appreciate you adding Fedora to the installation documentation.
Thanks,
-fuller

add Fedora Linux to installation

---

snap/snapcraft.yaml

The Oauth dance requires a temporary local HTTP server to be started and
the current snap settings were not allowing it.
Adding network-bind to the list of connections fixes the issue.
Fixes #261
If someone wants to test:
```bash
rm -f $HOME/snap/gmailctl/current/.gmailctl/token.json
snapcraft
snap install --dangerous ./gmailctl_v0.10.4-*.snap
gmailctl init
```

snap: add network-bind plug

---

cmd/gmailctl/cmd/config.go
internal/engine/cfgtest/cfgtest.go
internal/engine/cfgtest/exec_test.go
internal/engine/cfgtest/testdata/fail.jsonnet
internal/errors/err.go
internal/errors/err_test.go

When running `gmactl test`, do not exit after the first error, but accumulate all the errors.

Improve config tests output

---

README.md

- Add to `README.md` text, footnote and example on how to import a filter from a `.libjsonnet` file.
Showing this can be useful as the user can programmatically their filters and add them easily to the `config.jsonnet`file
- Also, improves footnote `2`

Add footnote on importing from `.libjsonnet` files

---

cmd/gmailctl-config-migrate/import.go
cmd/gmailctl-config-migrate/v1alpha2/import_test.go
cmd/gmailctl-config-migrate/v1alpha3/import_test.go
cmd/gmailctl/cmd/edit_cmd.go
integration_test.go
internal/data/lib_test.go
internal/engine/api/auth.go
internal/engine/cfgtest/cfgtest.go
internal/engine/cfgtest/exec_test.go
internal/engine/config/read.go

Suppose we have a rule configured to label messages with `oops-bad-label`, and a test that checks they're labeled with `yep-correct-label`. So before this change you would get:
--- want
+++ got
...
"labels": [
-   "oops-bad-label"
+   "yep-correct-label"
]
To make this match the usual logic of automated testing (especially Go's "want" and "got"), we would like the "want" section to be "what the test describes should happen". Therefore, with this change, we get this output:
--- want
+++ got
...
"labels": [
-   "yep-correct-label"
+   "oops-bad-label"
]

Reverse "want" and "got" in test failures

---

internal/errors/err.go

The buffer pool wasn't correctly used, as buffers were put back in
without being reset. This would result in errors with stale descriptions
coming from previous errors.

Fix buffer handling in internal/errors.

---

cmd/gmailctl/localcred/local_provider.go

Awesome project, thanks for that! This is just a small typo fix in the help text of the `init` command, printed if no credentials are set.

fix: typo in missing credentials help text

---

internal/engine/filter/convert.go
internal/engine/filter/convert_test.go

Reverts mbrt/gmailctl#260. See https://github.com/mbrt/gmailctl/issues/66#issuecomment-1293358400 and following for the discussion.

Revert "check for undesirable quotes"

---

internal/engine/filter/convert.go
internal/engine/filter/convert_test.go

Gmail has this weird behavior:
* `from: foo+bar` is equivalent to `from:foo OR from:bar`
* `from foo+bar@google.com` is not (just searches the full address).
This change accounts for this behavior and automatically quotes the
plus sign, only when outside of full email addresses. This should match
users expectations a lot better.

Quote plus sign automatically.

---

cmd/gmailctl/cmd/apply_cmd.go
cmd/gmailctl/cmd/debug_cmd.go
cmd/gmailctl/cmd/diff_cmd.go
cmd/gmailctl/cmd/edit_cmd.go
integration_test.go
internal/engine/apply/apply.go
internal/engine/filter/diff.go
internal/engine/filter/diff_test.go
internal/engine/filter/filter.go
internal/engine/filter/filter_test.go
internal/graph/munkres.go

When creating a complicated search criteria, it can be helpful to verify that it matches the emails. If you specify `--debug` on diff, apply, edit commands, URL to Gmail search will be displayed in the diff.
Fixes #407

Add `--debug` flag to display Gmail search URL

---

cmd/gmailctl/cmd/root_cmd.go

It is erroring with the message `Error: configuring the main config directory: mkdir : no such file or directory` because of an inverted comparison accidentally introduced in commit f713dc603cbca2879fcff0c67eb877677d987765.

Fix initialization of cfgDir

---

cmd/gmailctl/cmd/apply_cmd.go
cmd/gmailctl/cmd/diff_cmd.go
cmd/gmailctl/cmd/edit_cmd.go
integration_test.go
internal/engine/apply/apply.go
internal/engine/filter/diff.go
internal/engine/filter/diff_test.go

This adds a `--context` option to the `diff` subcommand and a `--diff-context` option to the `apply` and `edit` commands. The option allows the number of lines of diff context to be customized, which is helpful for verifying the correctness of changes to more complex filters.

Add context option for filter diffs

---

cmd/gmailctl/cmd/api_provider.go
cmd/gmailctl/cmd/init_cmd.go
cmd/gmailctl/localcred/local_provider.go
cmd/gmailctl/localcred/oauth2_server.go

Specifying a port is necessary when running in a Docker container

✨ Allowing to specify a port for OAuth server
