README.md
I admit that I am unsure is it correct and it is untested.
=> attempt to better describe syntax

pkg/export/xml/marshal.go, pkg/export/xml/marshal_test.go
=> fix missing newline from export

cmd/gmailctl/cmd/edit_cmd.go
=> Add support for args in $EDITOR

cmd/gmailctl/cmd/apply_cmd.go, cmd/gmailctl/cmd/config.go, cmd/gmailctl/cmd/debug_cmd.go, cmd/gmailctl/cmd/diff_cmd.go, cmd/gmailctl/cmd/edit_cmd.go, cmd/gmailctl/cmd/export_cmd.go, cmd/gmailctl/integration_test.go, pkg/config/lib_test.go, pkg/config/read.go
=> Fix apply with jsonnet config

cmd/gmailctl/cmd/apply_cmd.go, cmd/gmailctl/cmd/diff_cmd.go, cmd/gmailctl/cmd/edit_cmd.go, cmd/gmailctl/cmd/upstream.go, pkg/export/api/api_import.go, pkg/export/api/api_import_test.go
=> Avoid crashing in presence of broken filters upstream.

README.md
Includes info on other commands.
=> Provide some more usage details in README

README.md, pkg/export/api/api_export.go, pkg/export/api/api_export_test.go, pkg/export/api/api_import.go, pkg/export/api/api_import_test.go, pkg/export/xml/consts.go, pkg/export/xml/marshal.go, pkg/export/xml/marshal_test.go, pkg/filter/convert.go, pkg/filter/convert_test.go, pkg/filter/filter.go, pkg/rimport/rimport.go, testdata/local.bigdiffj.diff, testdata/local.bigdiffj.jsonnet, testdata/local.deleteall.diff
This is a ripoff and fix of #58.
Closes #56.
=> Implement forward action

pkg/export/api/api_import.go, pkg/export/api/api_import_test.go, pkg/export/api/api_test.go
=> Has attachment

pkg/config/v1alpha2/config.go, pkg/export/api/api_import.go
This makes the various bits more maintainable and fixes a crash
on array fields.
=> Refactor reflect usage.

pkg/config/read.go
Unfortunately not all errors get this context (e.g. unknown field
doesn't add any information, so we can't extract it).
This is I believe the best we can do, unless Jsonnet adds more
support for unmarshalling directly into structs instead of going
through JSON.
Close #53.
=> Add context to JSON error messages.

go.mod, go.sum, pkg/filter/diff.go, pkg/filter/diff_test.go, testdata/local.bigdiff.diff, testdata/local.bigdiffj.diff, testdata/local.deleteall.diff
Hashing a struct can be done in 3 lines, so dropping the dependency.
=> Remove structhash dependency.

go.mod
=> Set minimum go version to 1.13.

pkg/api/api.go
=> Add details to label creation / edit errors.

go.sum
relates to https://github.com/Homebrew/homebrew-core/pull/68047
=> fix: update go.sum

.github/workflows/codeql-analysis.yml, .github/workflows/go.yml, .github/workflows/lsif.yml, .github/workflows/stale.yml
Additionally removed writing the status for coverage.
It wasn't working properly on forks.
=> Add permissions to GH actions.

cmd/gmailctl/cmd/init_cmd.go
Closes #77.
Add `--update-lib` flag to `gmailctl init` to allow updating / resetting the gmailct.libsonnet file in users configuration.
=> Add --update-lib to gmailctl init

README.md
=> Advertise macports install option

internal/engine/filter/convert.go, internal/engine/filter/convert_test.go
=> Skip quoting if args are already quoted.

cmd/gmailctl/localcred/local_provider.go
The error is now the first line and more details come later.
=> Make init message less confusing

.github/workflows/go.yml
Also get rid the old handrolled code coverage report.
=> Onboard to codecov
